manual dhcpc instead of ipam dhcp plugin

diff --git a/manifests/samba-honeypot.yaml b/manifests/samba-honeypot.yaml
--- a/manifests/samba-honeypot.yaml
+++ b/manifests/samba-honeypot.yaml
@@ -19,30 +19,6 @@ spec:
     requests:
       storage: 100Mi
 ---
-apiVersion: "k8s.cni.cncf.io/v1"
-kind: NetworkAttachmentDefinition
-metadata:
-  name: macvlan-conf
-  namespace: samba-honeypot
-  labels:
-    app: samba-honeypot
-spec:
-  config: '{
-      "cniVersion": "0.3.0",
-      "type": "macvlan",
-      "mode": "bridge",
-      "master": "eno1",
-      "ipam": {
-        "type": "dhcp",
-        "provide": [
-          {
-            "option": "host-name",
-            "value": "fileserver"
-          }
-        ]
-      }
-    }'
----
 # Configuration for the samba domain member pod.
 apiVersion: v1
 kind: ConfigMap
@@ -56,52 +32,86 @@ data:
     {
       "samba-container-config": "v0",
       "configs": {
-        "demo": {
+        "sambasrv": {
           "shares": [
             "share"
           ],
           "globals": [
             "default"
           ],
-          "instance_name": "SAMBA"
-        }
-      },
-      "shares": {
-        "share": {
-          "options": {
-            "path": "/share",
-            "public": "yes",
-            "browseable": "yes",
-            "read only": "no",
-            "guest ok": "yes",
-            "writeable": "yes",
-            "create mask": "666",
-            "directory mask": "777",
-            "force user": "sambauser",
-            "force group": "sambauser"
-          }
+          "instance_name": "SAMBASRV"
         }
       },
       "globals": {
         "default": {
           "options": {
             "workgroup": "WORKGROUP",
-            "security": "user",
+            "server string": "Samba Server",
+            "server role": "standalone server",
+            "guest account": "guest",
             "map to guest": "Bad User",
-            "guest account": "sambauser"
+            "bind interfaces only": "yes",
+            "interfaces": "lo net1",
+            "wins support": "yes",
+            "browseable": "yes"
+          }
+        }
+      },
+      "shares": {
+        "share": {
+          "options": {
+            "comment": "All the files.",
+            "path": "/share",
+            "public": "yes",
+            "browseable": "yes",
+            "guest only": "yes",
+            "writeable": "yes",
+            "force create mode": "0666",
+            "force directory mode": "0777"
           }
         }
       },
       "users": {
         "all_entries": [
           {
-            "name": "sambauser",
-            "password": "samba"
+            "name": "guest",
+            "password": "password"
           }
         ]
       },
       "_footer": 1
     }
+---
+# DHCP interface configuration script
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: udhcpc-scripts
+  namespace: samba-honeypot
+  labels:
+    app: samba-honeypot
+data:
+  default.script: |
+    #!/bin/sh
+    [ -n "$1" ] || { echo "Error: should be called from udhcpc"; exit 1; }
+
+    NETMASK=""
+    [ -n "$subnet" ] && NETMASK="netmask $subnet"
+    BROADCAST="broadcast +"
+    [ -n "$broadcast" ] && BROADCAST="broadcast $broadcast"
+
+    case "$1" in
+      deconfig)
+        echo "Setting IP address 0.0.0.0 on $interface"
+        ifconfig $interface 0.0.0.0
+        ;;
+
+      renew|bound)
+        echo "Setting IP address $ip on $interface"
+        ifconfig $interface $ip $NETMASK $BROADCAST
+    esac
+
+    exit 0
 ---
 apiVersion: apps/v1
 kind: Deployment
@@ -120,16 +130,13 @@ spec:
       labels:
         app: samba-honeypot
       annotations:
-        k8s.v1.cni.cncf.io/networks: macvlan-conf
+        k8s.v1.cni.cncf.io/networks: honeynet/macvlan
     spec:
       shareProcessNamespace: true
       containers:
         - image: quay.io/samba.org/samba-server:latest
           name: smb
-          command:
-          - "samba-container"
-          - "run"
-          - "smbd"
+          command: ["samba-container", "run", "smbd"]
           securityContext:
             allowPrivilegeEscalation: true
           volumeMounts:
@@ -141,12 +148,10 @@ spec:
             name: samba-state-dir
           - mountPath: "/run/samba/winbindd"
             name: samba-sockets-dir
+
         - image: quay.io/samba.org/samba-server:latest
           name: winbind
-          command:
-          - "samba-container"
-          - "run"
-          - "winbindd"
+          command: ["samba-container", "run", "winbindd"]
           securityContext:
             allowPrivilegeEscalation: true
           volumeMounts:
@@ -156,11 +161,49 @@ spec:
             name: samba-state-dir
           - mountPath: "/run/samba/winbindd"
             name: samba-sockets-dir
+
+        - image: busybox
+          name: dhcp-client
+          command: [
+            "udhcpc",
+            "-i", "net1", # Interface to use
+            "-B", # Request broadcast replies (so everyone sees us)
+            "-T", "5", # Pause between packets
+            "-R", # Release IP on exit
+            "-f", # Run in foreground
+            "-a", # Validate offerred address with ARP ping (so everyone sees us)
+            "-O", "12", # request Host Name
+            "-O", "15", # request Domain Name
+            "-O", "42", # request NTP Servers
+            "-O", "119", # request Doman Search
+            "-O", "120", # request SIP Servers
+            "-x", "hostname:sambasrv", # provide option 22
+            # "-x", "lease:60", # request short 60-second lease
+            "-F", "sambasrv", # Ask server to update DNS mapping for "fileserver"
+            "-V", "Microsloth", # Vendor identifier (instead of udhcp)
+          ]
+          volumeMounts:
+          - mountPath: "/usr/share/udhcpc/"
+            name: udhcpc-scripts
+          securityContext:
+            allowPrivilegeEscalation: true
+            capabilities:
+              add: ["NET_BIND_SERVICE", "NET_BROADCAST", "NET_ADMIN"]
+        
+        - image: jonasped/wsdd
+          name: wsdd
+          env:
+          - name: WSDD_ARGS
+            value: "--interface net1 --hostname SAMBASRV --workgroup WORKGROUP"
+          securityContext:
+            allowPrivilegeEscalation: true
+            capabilities:
+              add: ["NET_BIND_SERVICE", "NET_BROADCAST"]
+            
       initContainers:
         - image: quay.io/samba.org/samba-server:latest
           name: init
-          args:
-          - "init"
+          args: ["init"]
           securityContext:
             allowPrivilegeEscalation: true
           volumeMounts:
@@ -185,3 +228,8 @@ spec:
     #  - emptyDir:
     #      medium: Memory
     #    name: samba-sharedir
+
+      - name: udhcpc-scripts
+        configMap:
+          name: udhcpc-scripts
+          defaultMode: 0744
